#! /bin/sh
#
# This is the postrm script for the Debian GNU/Linux dc package
#
# Written by John G. Hasler    
# Previous versions written by Dirk Eddelbuettel, Bill Mitchell, 
# Austin Donnelly and James Troup

set -e

#DEBHELPER#

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
 	if [ -x /usr/bin/update-menus ]
 	then
 	    update-menus
 	fi
        ;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
	;;
esac
